@startuml

class main {
    + main()
}

class board {
    + board_init()
}

class board_config {
}

class button {
    + button_init()
    + button_set_evt_cb()
    + button_enable_evt()
    + button_disable_evt()
}

class recorder {
    + recorder_init()
    + recorder_set_evt_cb()
    + recorder_run()
    + recorder_start()
    + recorder_stop()
}

class rec_timer {
    + rec_timer_init()
    + rec_timer_set_cb()
    + rec_timer_start()
    + rec_timer_stop()
}

class rec_storage {
    + rec_storage_init()
    + rec_storage_start_saving()
    + rec_storege_save()
    + rec_storage_stop_saving()
}

class mic {
    + mic_init()
    + mic_start_stream()
    + mic_stop_stream()
    + mic_get_data()
}

main --> recorder
main --> board
main --> button

recorder --> rec_timer
recorder --> mic
recorder --> rec_storage

board_config ..> mic
board_config ..> rec_storage
board_config ..> button

@enduml