@startuml fw_architecture

interface main {
    + main()
}

interface board {
    + board_init()
    + board_button_init()
    + board_button_set_evt_cb()
    + board_button_enable_evt()
    + board_button_disable_evt()
    + board_led_init()
    + board_led_blink_enable()
    + board_led_blink_disable()
    + baard_mic_init()
    + baard_mic_start_stream()
    + baard_mic_stop_stream()
    + board_sd_init()
    + board_sd_read_block()
    + board_sd_write_block()
    + board_sd_erase()
    + board_sd_is_busy()
}

interface recorder {
    + recorder_init()
    + recorder_start()
    + recorder_stop()
    + recorder_process()
    + recorder_get_state()
}

interface rec_timer {
    + rec_timer_init()
    + rec_timer_set_cb()
    + rec_timer_start()
    + rec_timer_stop()
}

interface rec_storage {
    + rec_storage_init()
    + rec_storage_start_saving()
    + rec_storege_save_samples()
    + rec_storage_stop_saving()
}

main --> recorder
main --> board

recorder --> rec_timer
recorder --> board
recorder --> rec_storage
rec_storage --> board

@enduml